name: Update News

on:
  workflow_dispatch:

  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests beautifulsoup4

      - run: python scraper.py

      - run: ls -la
- name: Commit changes
  run: |
    git config user.name github-actions
    git config user.email actions@github.com
    git add .
    git commit -m "update news" || exit 0
    git pull --rebase origin main
    git push origin main
      
